### ISSUE TITLE
Does this work for HL7v3 or is there a similar tool?

### ISSUE THREAD

**Issue by emeria** [microsoft/vscode-azurehealthcareapis-tools#31]
Does this work for HL7v3 (or is there a similar tool)? My team has been working on mapping CCDA files into FHIR the best we can, but I saw this tool through the Azure API for FHIR service pages and figured I would ask.

**Comment by yankunhuang-pku** [comment]
At present, it only supports HL7v2, but the feature of converting CCDA files to FHIR is under development, which will be released in the near future.

**Comment by yankunhuang-pku** [comment]
@emeria The latest extension (1.3.0) has been released. which supports for converting data from C-CDA to FHIR with liquid templates
