### ISSUE TITLE
Not able to convert FHIR bundle data

### ISSUE THREAD

**Issue by rishabsood9** [microsoft/vscode-azurehealthcareapis-tools#62]
Hi Team,

The liquid template is not working with bundle entry array looping correctly! But if I change the name of Resource or ResourceType to something else it gives the correct output.

**Comment by yankunhuang-pku** [comment]
Could you provide your input data, output data and templates to let us understand your issue better?

**Comment by irenepjoseph** [comment]
@rishabsood9, do you have additional information to share?
